### ISSUE TITLE
global name 'lexemes' is not defined

### ISSUE THREAD

**Issue by quizzicol** [interrogator/corpkit#26]
Trying to use corpkit with a 64 bit Python 2.7.11 Anaconda installation.

on 'from dictionaries.process_types import processes' I get 

**'NameError: global name 'lexemes' is not defined'**

**Comment by interrogator** [comment]
Ah. I've found the problem. Should be able to fix shortly.

**Comment by interrogator** [comment]
It was an error in the `setup.py` file, which wasn't finding the data files in `corpkit/dictionaries` and adding them to the bundle. This should be fixed by 5ff938f, and in `pip install corpkit` (v. 1.89) as well. Closing, but please let me know if there are any other issues!
